services:
  vibrain:
    build: .
    ports:
      - "1323:1323"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - vibrain-data:/var/lib/postgresql/data

volumes:
  vibrain-data:

