services:
  vibrain:
    image: vaayne/vibrain:latest
    build: .
    ports:
      - "1323:1323"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=1323
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
  browserless:
    image:  gcr.docker.vaayne.com/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    ports:
      - "9222:9222"
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      # - --hide-scrollbars
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - vibrain-data:/var/lib/postgresql/data

volumes:
  vibrain-data:
