services:
  recally:
    image: vaayne/recally:latest
    build: .
    ports:
      - "13233:1323"
    environment:
      - SERVICE_HOST=0.0.0.0
      - SERVICE_PORT=1323
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - BROWSER_CONTROL_URL=http://browser:7317
    env_file:
      - .env
    volumes:
      - .env:/app/.env
    depends_on:
      - postgres
      - browser
  browser:
    image:  ghcr.docker.vaayne.com/go-rod/rod:latest
    restart: unless-stopped
    ports:
      - "17317:7317"
  postgres:
    image: paradedb/paradedb:latest-pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15433:5432"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
