/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssistantsAssistantDTO
 */
export interface AssistantsAssistantDTO {
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    id?: string;
    /**
     * 
     * @type {object}
     * @memberof AssistantsAssistantDTO
     */
    metadata?: object;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    systemPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantsAssistantDTO
     */
    userId?: string;
}

/**
 * Check if a given object implements the AssistantsAssistantDTO interface.
 */
export function instanceOfAssistantsAssistantDTO(value: object): value is AssistantsAssistantDTO {
    return true;
}

export function AssistantsAssistantDTOFromJSON(json: any): AssistantsAssistantDTO {
    return AssistantsAssistantDTOFromJSONTyped(json, false);
}

export function AssistantsAssistantDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssistantsAssistantDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'model': json['model'] == null ? undefined : json['model'],
        'name': json['name'] == null ? undefined : json['name'],
        'systemPrompt': json['system_prompt'] == null ? undefined : json['system_prompt'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function AssistantsAssistantDTOToJSON(value?: AssistantsAssistantDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': value['createdAt'],
        'description': value['description'],
        'id': value['id'],
        'metadata': value['metadata'],
        'model': value['model'],
        'name': value['name'],
        'system_prompt': value['systemPrompt'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
    };
}

