/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AssistantsAssistant
 */
export interface AssistantsAssistant {
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  description?: string;
  /**
   *
   * @type {object}
   * @memberof AssistantsAssistant
   */
  metadata?: object;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  model?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  systemPrompt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsAssistant
   */
  uuid?: string;
}

/**
 * Check if a given object implements the AssistantsAssistant interface.
 */
export function instanceOfAssistantsAssistant(
  value: object,
): value is AssistantsAssistant {
  return true;
}

export function AssistantsAssistantFromJSON(json: any): AssistantsAssistant {
  return AssistantsAssistantFromJSONTyped(json, false);
}

export function AssistantsAssistantFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsAssistant {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json["created_at"] == null ? undefined : json["created_at"],
    description: json["description"] == null ? undefined : json["description"],
    metadata: json["metadata"] == null ? undefined : json["metadata"],
    model: json["model"] == null ? undefined : json["model"],
    name: json["name"] == null ? undefined : json["name"],
    systemPrompt:
      json["system_prompt"] == null ? undefined : json["system_prompt"],
    updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
    uuid: json["uuid"] == null ? undefined : json["uuid"],
  };
}

export function AssistantsAssistantToJSON(
  value?: AssistantsAssistant | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"],
    description: value["description"],
    metadata: value["metadata"],
    model: value["model"],
    name: value["name"],
    system_prompt: value["systemPrompt"],
    updated_at: value["updatedAt"],
    user_id: value["userId"],
    uuid: value["uuid"],
  };
}
