/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AssistantsThreadMessage
 */
export interface AssistantsThreadMessage {
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  model?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  role?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  text?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  threadId?: string;
  /**
   *
   * @type {number}
   * @memberof AssistantsThreadMessage
   */
  token?: number;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThreadMessage
   */
  userId?: string;
}

/**
 * Check if a given object implements the AssistantsThreadMessage interface.
 */
export function instanceOfAssistantsThreadMessage(
  value: object,
): value is AssistantsThreadMessage {
  return true;
}

export function AssistantsThreadMessageFromJSON(
  json: any,
): AssistantsThreadMessage {
  return AssistantsThreadMessageFromJSONTyped(json, false);
}

export function AssistantsThreadMessageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsThreadMessage {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json["created_at"] == null ? undefined : json["created_at"],
    model: json["model"] == null ? undefined : json["model"],
    role: json["role"] == null ? undefined : json["role"],
    text: json["text"] == null ? undefined : json["text"],
    threadId: json["thread_id"] == null ? undefined : json["thread_id"],
    token: json["token"] == null ? undefined : json["token"],
    updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
  };
}

export function AssistantsThreadMessageToJSON(
  value?: AssistantsThreadMessage | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    created_at: value["createdAt"],
    model: value["model"],
    role: value["role"],
    text: value["text"],
    thread_id: value["threadId"],
    token: value["token"],
    updated_at: value["updatedAt"],
    user_id: value["userId"],
  };
}
