/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssistantsThreadMessageDTO } from "./AssistantsThreadMessageDTO";
import {
  AssistantsThreadMessageDTOFromJSON,
  AssistantsThreadMessageDTOFromJSONTyped,
  AssistantsThreadMessageDTOToJSON,
} from "./AssistantsThreadMessageDTO";

/**
 *
 * @export
 * @interface AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
 */
export interface AssistantsAssistantIdThreadsThreadIdMessagesPost201Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
   */
  code?: number;
  /**
   *
   * @type {AssistantsThreadMessageDTO}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
   */
  data?: AssistantsThreadMessageDTO;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesPost201Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the AssistantsAssistantIdThreadsThreadIdMessagesPost201Response interface.
 */
export function instanceOfAssistantsAssistantIdThreadsThreadIdMessagesPost201Response(
  value: object,
): value is AssistantsAssistantIdThreadsThreadIdMessagesPost201Response {
  return true;
}

export function AssistantsAssistantIdThreadsThreadIdMessagesPost201ResponseFromJSON(
  json: any,
): AssistantsAssistantIdThreadsThreadIdMessagesPost201Response {
  return AssistantsAssistantIdThreadsThreadIdMessagesPost201ResponseFromJSONTyped(
    json,
    false,
  );
}

export function AssistantsAssistantIdThreadsThreadIdMessagesPost201ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsAssistantIdThreadsThreadIdMessagesPost201Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data:
      json["data"] == null
        ? undefined
        : AssistantsThreadMessageDTOFromJSON(json["data"]),
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function AssistantsAssistantIdThreadsThreadIdMessagesPost201ResponseToJSON(
  value?: AssistantsAssistantIdThreadsThreadIdMessagesPost201Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data: AssistantsThreadMessageDTOToJSON(value["data"]),
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
