/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssistantsThread } from "./AssistantsThread";
import {
  AssistantsThreadFromJSON,
  AssistantsThreadFromJSONTyped,
  AssistantsThreadToJSON,
} from "./AssistantsThread";

/**
 *
 * @export
 * @interface AssistantsAssistantIdThreadsGet200Response
 */
export interface AssistantsAssistantIdThreadsGet200Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof AssistantsAssistantIdThreadsGet200Response
   */
  code?: number;
  /**
   *
   * @type {Array<AssistantsThread>}
   * @memberof AssistantsAssistantIdThreadsGet200Response
   */
  data?: Array<AssistantsThread>;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof AssistantsAssistantIdThreadsGet200Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof AssistantsAssistantIdThreadsGet200Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof AssistantsAssistantIdThreadsGet200Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the AssistantsAssistantIdThreadsGet200Response interface.
 */
export function instanceOfAssistantsAssistantIdThreadsGet200Response(
  value: object,
): value is AssistantsAssistantIdThreadsGet200Response {
  return true;
}

export function AssistantsAssistantIdThreadsGet200ResponseFromJSON(
  json: any,
): AssistantsAssistantIdThreadsGet200Response {
  return AssistantsAssistantIdThreadsGet200ResponseFromJSONTyped(json, false);
}

export function AssistantsAssistantIdThreadsGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsAssistantIdThreadsGet200Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(AssistantsThreadFromJSON),
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function AssistantsAssistantIdThreadsGet200ResponseToJSON(
  value?: AssistantsAssistantIdThreadsGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(AssistantsThreadToJSON),
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
