/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssistantsThreadMessage } from "./AssistantsThreadMessage";
import {
  AssistantsThreadMessageFromJSON,
  AssistantsThreadMessageFromJSONTyped,
  AssistantsThreadMessageToJSON,
} from "./AssistantsThreadMessage";

/**
 *
 * @export
 * @interface AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
 */
export interface AssistantsAssistantIdThreadsThreadIdMessagesGet200Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
   */
  code?: number;
  /**
   *
   * @type {Array<AssistantsThreadMessage>}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
   */
  data?: Array<AssistantsThreadMessage>;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof AssistantsAssistantIdThreadsThreadIdMessagesGet200Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the AssistantsAssistantIdThreadsThreadIdMessagesGet200Response interface.
 */
export function instanceOfAssistantsAssistantIdThreadsThreadIdMessagesGet200Response(
  value: object,
): value is AssistantsAssistantIdThreadsThreadIdMessagesGet200Response {
  return true;
}

export function AssistantsAssistantIdThreadsThreadIdMessagesGet200ResponseFromJSON(
  json: any,
): AssistantsAssistantIdThreadsThreadIdMessagesGet200Response {
  return AssistantsAssistantIdThreadsThreadIdMessagesGet200ResponseFromJSONTyped(
    json,
    false,
  );
}

export function AssistantsAssistantIdThreadsThreadIdMessagesGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsAssistantIdThreadsThreadIdMessagesGet200Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data:
      json["data"] == null
        ? undefined
        : (json["data"] as Array<any>).map(AssistantsThreadMessageFromJSON),
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function AssistantsAssistantIdThreadsThreadIdMessagesGet200ResponseToJSON(
  value?: AssistantsAssistantIdThreadsThreadIdMessagesGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data:
      value["data"] == null
        ? undefined
        : (value["data"] as Array<any>).map(AssistantsThreadMessageToJSON),
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
