/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssistantsThreadMessage } from "./AssistantsThreadMessage";
import {
  AssistantsThreadMessageFromJSON,
  AssistantsThreadMessageFromJSONTyped,
  AssistantsThreadMessageToJSON,
} from "./AssistantsThreadMessage";

/**
 *
 * @export
 * @interface AssistantsThread
 */
export interface AssistantsThread {
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  assistantId?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  createdAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  description?: string;
  /**
   *
   * @type {Array<AssistantsThreadMessage>}
   * @memberof AssistantsThread
   */
  messages?: Array<AssistantsThreadMessage>;
  /**
   *
   * @type {object}
   * @memberof AssistantsThread
   */
  metadata?: object;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  model?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  systemPrompt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  updatedAt?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  userId?: string;
  /**
   *
   * @type {string}
   * @memberof AssistantsThread
   */
  uuid?: string;
}

/**
 * Check if a given object implements the AssistantsThread interface.
 */
export function instanceOfAssistantsThread(
  value: object,
): value is AssistantsThread {
  return true;
}

export function AssistantsThreadFromJSON(json: any): AssistantsThread {
  return AssistantsThreadFromJSONTyped(json, false);
}

export function AssistantsThreadFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AssistantsThread {
  if (json == null) {
    return json;
  }
  return {
    assistantId:
      json["assistant_id"] == null ? undefined : json["assistant_id"],
    createdAt: json["created_at"] == null ? undefined : json["created_at"],
    description: json["description"] == null ? undefined : json["description"],
    messages:
      json["messages"] == null
        ? undefined
        : (json["messages"] as Array<any>).map(AssistantsThreadMessageFromJSON),
    metadata: json["metadata"] == null ? undefined : json["metadata"],
    model: json["model"] == null ? undefined : json["model"],
    name: json["name"] == null ? undefined : json["name"],
    systemPrompt:
      json["system_prompt"] == null ? undefined : json["system_prompt"],
    updatedAt: json["updated_at"] == null ? undefined : json["updated_at"],
    userId: json["user_id"] == null ? undefined : json["user_id"],
    uuid: json["uuid"] == null ? undefined : json["uuid"],
  };
}

export function AssistantsThreadToJSON(value?: AssistantsThread | null): any {
  if (value == null) {
    return value;
  }
  return {
    assistant_id: value["assistantId"],
    created_at: value["createdAt"],
    description: value["description"],
    messages:
      value["messages"] == null
        ? undefined
        : (value["messages"] as Array<any>).map(AssistantsThreadMessageToJSON),
    metadata: value["metadata"],
    model: value["model"],
    name: value["name"],
    system_prompt: value["systemPrompt"],
    updated_at: value["updatedAt"],
    user_id: value["userId"],
    uuid: value["uuid"],
  };
}
