/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpserverUserResponse } from './HttpserverUserResponse';
import {
    HttpserverUserResponseFromJSON,
    HttpserverUserResponseFromJSONTyped,
    HttpserverUserResponseToJSON,
} from './HttpserverUserResponse';

/**
 * 
 * @export
 * @interface AuthLoginPost200Response
 */
export interface AuthLoginPost200Response {
    /**
     * Code is an integer value that represents the HTTP status code.
     * @type {number}
     * @memberof AuthLoginPost200Response
     */
    code?: number;
    /**
     * 
     * @type {HttpserverUserResponse}
     * @memberof AuthLoginPost200Response
     */
    data?: HttpserverUserResponse;
    /**
     * Error is an error value that represents the error of the response.
     * @type {object}
     * @memberof AuthLoginPost200Response
     */
    error?: object;
    /**
     * Message is a string value that represents the message of the response.
     * @type {string}
     * @memberof AuthLoginPost200Response
     */
    message?: string;
    /**
     * Success is a boolean value that indicates whether the request was successful.
     * @type {boolean}
     * @memberof AuthLoginPost200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the AuthLoginPost200Response interface.
 */
export function instanceOfAuthLoginPost200Response(value: object): value is AuthLoginPost200Response {
    return true;
}

export function AuthLoginPost200ResponseFromJSON(json: any): AuthLoginPost200Response {
    return AuthLoginPost200ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : HttpserverUserResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function AuthLoginPost200ResponseToJSON(value?: AuthLoginPost200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': HttpserverUserResponseToJSON(value['data']),
        'error': value['error'],
        'message': value['message'],
        'success': value['success'],
    };
}

