/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HttpserverLoginRequest
 */
export interface HttpserverLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof HttpserverLoginRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof HttpserverLoginRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the HttpserverLoginRequest interface.
 */
export function instanceOfHttpserverLoginRequest(value: object): value is HttpserverLoginRequest {
    return true;
}

export function HttpserverLoginRequestFromJSON(json: any): HttpserverLoginRequest {
    return HttpserverLoginRequestFromJSONTyped(json, false);
}

export function HttpserverLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HttpserverLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function HttpserverLoginRequestToJSON(value?: HttpserverLoginRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

