/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { JinasearcherContent } from "./JinasearcherContent";
import {
  JinasearcherContentFromJSON,
  JinasearcherContentFromJSONTyped,
  JinasearcherContentToJSON,
} from "./JinasearcherContent";

/**
 *
 * @export
 * @interface ToolsWebSearchGet200Response
 */
export interface ToolsWebSearchGet200Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof ToolsWebSearchGet200Response
   */
  code?: number;
  /**
   *
   * @type {JinasearcherContent}
   * @memberof ToolsWebSearchGet200Response
   */
  data?: JinasearcherContent;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof ToolsWebSearchGet200Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof ToolsWebSearchGet200Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof ToolsWebSearchGet200Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the ToolsWebSearchGet200Response interface.
 */
export function instanceOfToolsWebSearchGet200Response(
  value: object,
): value is ToolsWebSearchGet200Response {
  return true;
}

export function ToolsWebSearchGet200ResponseFromJSON(
  json: any,
): ToolsWebSearchGet200Response {
  return ToolsWebSearchGet200ResponseFromJSONTyped(json, false);
}

export function ToolsWebSearchGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ToolsWebSearchGet200Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data:
      json["data"] == null
        ? undefined
        : JinasearcherContentFromJSON(json["data"]),
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function ToolsWebSearchGet200ResponseToJSON(
  value?: ToolsWebSearchGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data: JinasearcherContentToJSON(value["data"]),
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
