/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { JinareaderContent } from "./JinareaderContent";
import {
  JinareaderContentFromJSON,
  JinareaderContentFromJSONTyped,
  JinareaderContentToJSON,
} from "./JinareaderContent";

/**
 *
 * @export
 * @interface WebReaderGet200Response
 */
export interface WebReaderGet200Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof WebReaderGet200Response
   */
  code?: number;
  /**
   *
   * @type {JinareaderContent}
   * @memberof WebReaderGet200Response
   */
  data?: JinareaderContent;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof WebReaderGet200Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof WebReaderGet200Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof WebReaderGet200Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the WebReaderGet200Response interface.
 */
export function instanceOfWebReaderGet200Response(
  value: object,
): value is WebReaderGet200Response {
  return true;
}

export function WebReaderGet200ResponseFromJSON(
  json: any,
): WebReaderGet200Response {
  return WebReaderGet200ResponseFromJSONTyped(json, false);
}

export function WebReaderGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebReaderGet200Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data:
      json["data"] == null
        ? undefined
        : JinareaderContentFromJSON(json["data"]),
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function WebReaderGet200ResponseToJSON(
  value?: WebReaderGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data: JinareaderContentToJSON(value["data"]),
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
