/* tslint:disable */
/* eslint-disable */
/**
 * Vibrain API
 * This is a simple API for Vibrain project.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vibrain@vaayne.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WebSummaryGet200Response
 */
export interface WebSummaryGet200Response {
  /**
   * Code is an integer value that represents the HTTP status code.
   * @type {number}
   * @memberof WebSummaryGet200Response
   */
  code?: number;
  /**
   *
   * @type {string}
   * @memberof WebSummaryGet200Response
   */
  data?: string;
  /**
   * Error is an error value that represents the error of the response.
   * @type {object}
   * @memberof WebSummaryGet200Response
   */
  error?: object;
  /**
   * Message is a string value that represents the message of the response.
   * @type {string}
   * @memberof WebSummaryGet200Response
   */
  message?: string;
  /**
   * Success is a boolean value that indicates whether the request was successful.
   * @type {boolean}
   * @memberof WebSummaryGet200Response
   */
  success?: boolean;
}

/**
 * Check if a given object implements the WebSummaryGet200Response interface.
 */
export function instanceOfWebSummaryGet200Response(
  value: object,
): value is WebSummaryGet200Response {
  return true;
}

export function WebSummaryGet200ResponseFromJSON(
  json: any,
): WebSummaryGet200Response {
  return WebSummaryGet200ResponseFromJSONTyped(json, false);
}

export function WebSummaryGet200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): WebSummaryGet200Response {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"] == null ? undefined : json["code"],
    data: json["data"] == null ? undefined : json["data"],
    error: json["error"] == null ? undefined : json["error"],
    message: json["message"] == null ? undefined : json["message"],
    success: json["success"] == null ? undefined : json["success"],
  };
}

export function WebSummaryGet200ResponseToJSON(
  value?: WebSummaryGet200Response | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    code: value["code"],
    data: value["data"],
    error: value["error"],
    message: value["message"],
    success: value["success"],
  };
}
