name: Lint and Test

on: push

jobs:
    golangci:
        name: lint and test
        runs-on: ubicloud-standard-2
        steps:
            - uses: actions/checkout@v5

            - name: Setup mise
              uses: jdx/mise-action@v3
              with:
                  cache: true

            - name: Lint
              run: mise run lint:go

            - name: Test
              run: mise run test | tee test-results.txt

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: test-results.txt
